"""Static route catalog for governance jobs."""


def build_job_catalog() -> dict[str, object]:
    """Return the available governance job catalog."""
    return {
        "message": "Rule-based v1 governance jobs available in the current MVP.",
        "items": [
            {
                "name": "run_p0_demo",
                "method": "POST",
                "path": "/jobs/run-p0-demo",
                "description": "Run the rule-based P0 pipeline on built-in demo metadata.",
            },
            {
                "name": "run_p0_from_file",
                "method": "POST",
                "path": "/jobs/run-p0-from-file",
                "description": "Run the rule-based P0 pipeline on a local CSV or Excel file path.",
            },
            {
                "name": "run_p0_plus_mapping",
                "method": "POST",
                "path": "/jobs/run-p0-plus-mapping",
                "description": "Run the rule-based P0 pipeline plus P1 standard mapping on a local CSV or Excel file path.",
            },
            {
                "name": "run_p0_plus_mapping_plus_stg",
                "method": "POST",
                "path": "/jobs/run-p0-plus-mapping-plus-stg",
                "description": "Run the rule-based P0 pipeline, P1 standard mapping, and P1.5 STG structure suggestion on a local CSV or Excel file path.",
            },
            {
                "name": "run_p0_plus_mapping_plus_stg_with_review",
                "method": "POST",
                "path": "/jobs/run-p0-plus-mapping-plus-stg-with-review",
                "description": "Run the rule-based P0 pipeline, mapping, and STG suggestion while applying saved local review overrides.",
            },
            {
                "name": "run_p0_plus_mapping_plus_stg_plus_quality",
                "method": "POST",
                "path": "/jobs/run-p0-plus-mapping-plus-stg-plus-quality",
                "description": "Run the rule-based diagnosis, mapping, STG suggestion, and quality rule recommendation workflow on a local CSV or Excel file path.",
            },
            {
                "name": "run_p0_plus_mapping_plus_stg_plus_quality_with_review",
                "method": "POST",
                "path": "/jobs/run-p0-plus-mapping-plus-stg-plus-quality-with-review",
                "description": "Run the rule-based diagnosis, mapping, STG suggestion, and quality rule recommendation workflow while applying saved local review overrides.",
            },
            {
                "name": "run_mapping_only",
                "method": "POST",
                "path": "/jobs/run-mapping-only",
                "description": "Run the rule-based standard mapping workflow on a local CSV or Excel file path.",
            },
            {
                "name": "run_stg_only_from_mapping",
                "method": "POST",
                "path": "/jobs/run-stg-only-from-mapping",
                "description": "Run the rule-based mapping plus STG workflow without full diagnosis packaging.",
            },
            {
                "name": "run_quality_only_from_stg",
                "method": "POST",
                "path": "/jobs/run-quality-only-from-stg",
                "description": "Run the rule-based mapping, STG suggestion, and quality rule recommendation workflow without full diagnosis packaging.",
            },
            {
                "name": "run_quality_only_from_stg_with_review",
                "method": "POST",
                "path": "/jobs/run-quality-only-from-stg-with-review",
                "description": "Run quality rule recommendation with review replay without full diagnosis packaging.",
            },
            {
                "name": "run_governance_task",
                "method": "POST",
                "path": "/jobs/run-governance-task",
                "description": "Run a named workflow profile through the unified governance task router.",
            },
            {
                "name": "list_workflow_profiles",
                "method": "GET",
                "path": "/jobs/list-workflow-profiles",
                "description": "Return enabled workflow profiles for the unified governance router.",
            },
            {
                "name": "interpret_governance_task",
                "method": "POST",
                "path": "/jobs/interpret-governance-task",
                "description": "Interpret natural-language task text into a standard governance task request without executing it.",
            },
            {
                "name": "run_interpreted_governance_task",
                "method": "POST",
                "path": "/jobs/run-interpreted-governance-task",
                "description": "Interpret natural-language task text and then execute it through the unified governance task router.",
            },
            {
                "name": "agent_shell_plan",
                "method": "POST",
                "path": "/jobs/agent-shell/plan",
                "description": "Interpret task text and return a previewable execution plan without running it.",
            },
            {
                "name": "agent_shell_resolve_context",
                "method": "POST",
                "path": "/jobs/agent-shell/resolve-context",
                "description": "Interpret task text, resolve local session context, and return the resolved plan without executing it.",
            },
            {
                "name": "agent_shell_run",
                "method": "POST",
                "path": "/jobs/agent-shell/run",
                "description": "Interpret task text, build a plan, and execute only when validation and confirmation policy allow it.",
            },
            {
                "name": "agent_shell_session",
                "method": "GET",
                "path": "/jobs/agent-shell/session/{session_id}",
                "description": "Return a lightweight agent shell session overview.",
            },
            {
                "name": "list_tools",
                "method": "GET",
                "path": "/jobs/list-tools",
                "description": "Return enabled tool contract definitions for the local tool layer.",
            },
            {
                "name": "call_tool",
                "method": "POST",
                "path": "/jobs/call-tool",
                "description": "Call one local governance tool through the standardized tool executor.",
            },
            {
                "name": "capability_manifest",
                "method": "GET",
                "path": "/jobs/capability-manifest",
                "description": "Return the adapter-layer capability manifest for local external integration preparation.",
            },
            {
                "name": "tool_schemas_native",
                "method": "GET",
                "path": "/jobs/tool-schemas/native",
                "description": "Return native tool schemas exported from the local tool registry.",
            },
            {
                "name": "tool_schemas_openai",
                "method": "GET",
                "path": "/jobs/tool-schemas/openai",
                "description": "Return simplified OpenAI-style function schemas for local adapter use.",
            },
            {
                "name": "tool_schemas_mcp",
                "method": "GET",
                "path": "/jobs/tool-schemas/mcp",
                "description": "Return a lightweight MCP-style manifest for local adapter inspection.",
            },
            {
                "name": "invoke_native_tool",
                "method": "POST",
                "path": "/jobs/invoke-native-tool",
                "description": "Invoke one local governance tool through the native adapter shape.",
            },
            {
                "name": "invoke_openai_tool",
                "method": "POST",
                "path": "/jobs/invoke-openai-tool",
                "description": "Invoke one local governance tool through the simplified OpenAI-style adapter shape.",
            },
            {
                "name": "get_trace",
                "method": "GET",
                "path": "/jobs/trace/{trace_id}",
                "description": "Return one execution trace by trace id.",
            },
            {
                "name": "list_recent_traces",
                "method": "GET",
                "path": "/jobs/traces/recent",
                "description": "Return recent execution traces from the local audit store.",
            },
            {
                "name": "list_config_assets",
                "method": "GET",
                "path": "/jobs/config-assets",
                "description": "Return managed governance configuration assets from the local control plane.",
            },
            {
                "name": "get_config_asset",
                "method": "GET",
                "path": "/jobs/config-assets/{asset_name}",
                "description": "Return one managed governance configuration asset and its current content.",
            },
            {
                "name": "validate_config_asset",
                "method": "POST",
                "path": "/jobs/config-assets/{asset_name}/validate",
                "description": "Validate one managed governance configuration asset.",
            },
            {
                "name": "save_config_asset",
                "method": "POST",
                "path": "/jobs/config-assets/{asset_name}/save",
                "description": "Save one managed governance configuration asset after validation.",
            },
            {
                "name": "publish_config_asset",
                "method": "POST",
                "path": "/jobs/config-assets/{asset_name}/publish",
                "description": "Mark one managed governance configuration asset as published.",
            },
            {
                "name": "save_mapping_review",
                "method": "POST",
                "path": "/jobs/save-mapping-review",
                "description": "Persist local mapping review records to override storage.",
            },
            {
                "name": "save_stg_review",
                "method": "POST",
                "path": "/jobs/save-stg-review",
                "description": "Persist local STG review records to override storage.",
            },
            {
                "name": "list_review_summary",
                "method": "GET",
                "path": "/jobs/list-review-summary",
                "description": "Return basic counts from locally stored review overrides.",
            },
            {
                "name": "review_quality_rules",
                "method": "POST",
                "path": "/jobs/review-quality-rules",
                "description": "Review suggested quality rules and return confirmed quality rules.",
            },
            {
                "name": "export_confirmed_quality_rules",
                "method": "POST",
                "path": "/jobs/export-confirmed-quality-rules",
                "description": "Export confirmed quality rules as custom JSON or dbt tests YAML.",
            },
            {
                "name": "build_execution_ready_package",
                "method": "POST",
                "path": "/jobs/build-execution-ready-package",
                "description": "Build an execution-ready governance package from confirmed quality rules.",
            },
            {
                "name": "export_execution_ready_package",
                "method": "POST",
                "path": "/jobs/export-execution-ready-package",
                "description": "Export an execution-ready governance package as package JSON, manifest, or dbt YAML.",
            },
            {
                "name": "assess_governance_readiness",
                "method": "POST",
                "path": "/jobs/assess-governance-readiness",
                "description": "Assess governance readiness scores and classify governance gaps.",
            },
            {
                "name": "build_governance_work_package",
                "method": "POST",
                "path": "/jobs/build-governance-work-package",
                "description": "Build remediation actions and an exportable governance work package.",
            },
            {
                "name": "governance_readiness_summary",
                "method": "GET",
                "path": "/jobs/governance-readiness-summary",
                "description": "Return a lightweight summary placeholder for readiness/remediation capability.",
            },
            {
                "name": "build_governance_backlog",
                "method": "POST",
                "path": "/jobs/build-governance-backlog",
                "description": "Build local governance backlog items from remediation actions.",
            },
            {
                "name": "governance_backlog",
                "method": "GET",
                "path": "/jobs/governance-backlog",
                "description": "List persisted governance backlog items with optional filters.",
            },
            {
                "name": "update_governance_backlog_status",
                "method": "POST",
                "path": "/jobs/governance-backlog/{backlog_id}/status",
                "description": "Update one persisted governance backlog item status.",
            },
            {
                "name": "governance_backlog_summary",
                "method": "GET",
                "path": "/jobs/governance-backlog-summary",
                "description": "Return persisted governance backlog summary counts.",
            },
            {
                "name": "assess_governance_portfolio",
                "method": "POST",
                "path": "/jobs/assess-governance-portfolio",
                "description": "Assess backlog SLA, portfolio summary, and progress snapshot outputs.",
            },
            {
                "name": "generate_progress_snapshot",
                "method": "POST",
                "path": "/jobs/generate-progress-snapshot",
                "description": "Generate and optionally save a local governance progress snapshot.",
            },
            {
                "name": "governance_progress_snapshots",
                "method": "GET",
                "path": "/jobs/governance-progress-snapshots",
                "description": "List saved local governance progress snapshots.",
            },
            {
                "name": "governance_portfolio_summary",
                "method": "GET",
                "path": "/jobs/governance-portfolio-summary",
                "description": "Return current persisted backlog portfolio summary.",
            },
            {
                "name": "execution_package_summary",
                "method": "GET",
                "path": "/jobs/execution-package-summary",
                "description": "Return a lightweight summary placeholder for execution package capability.",
            },
            {
                "name": "quality_rule_review_summary",
                "method": "GET",
                "path": "/jobs/quality-rule-review-summary",
                "description": "Return quality rule review counts from stored overrides.",
            },
        ],
    }
