"""Aggregated routes for governance job execution.

This module keeps the historical `app.api.routes_jobs` import surface while the
route implementations live in smaller domain-focused modules.
"""

from fastapi import APIRouter

from app.api.job_requests import (
    AgentShellPlanRequest,
    AgentShellRunRequest,
    BatchGovernanceRequest,
    BatchSnapshotCompareRequest,
    ConfigAssetSaveRequest,
    ConfirmationTemplateRequest,
    ConfirmationWorkbookImportRequest,
    ConfirmedQualityRuleExportRequest,
    DomainPackMatchRequest,
    ExecutionPackageBuildRequest,
    ExecutionPackageExportRequest,
    FileRunRequest,
    GovernanceBacklogBuildRequest,
    GovernanceBacklogStatusUpdateRequest,
    GovernanceDeliveryPackageRequest,
    GovernancePortfolioAssessmentRequest,
    GovernanceReadinessAssessmentRequest,
    GovernanceWorkPackageBuildRequest,
    IntentTextRequest,
    MappingReviewSaveRequest,
    MetadataIntakeRequest,
    NativeToolInvokeRequest,
    OpenAIToolInvokeRequest,
    ProgressSnapshotRequest,
    ProjectTemplateRunRequest,
    QualityRuleReviewRequest,
    StgReviewSaveRequest,
)
from app.api.routes_jobs_backlog import (
    assess_governance_portfolio_route,
    build_governance_backlog_route,
    generate_progress_snapshot_route,
    governance_backlog_route,
    governance_backlog_summary_route,
    governance_portfolio_summary_route,
    governance_progress_snapshots_route,
    router as backlog_router,
    update_governance_backlog_status_route,
)
from app.api.routes_jobs_core import (
    interpret_governance_task,
    list_jobs,
    list_workflow_profiles,
    router as core_router,
    run_governance_task_route,
    run_interpreted_governance_task,
    run_mapping_only,
    run_p0_demo,
    run_p0_from_file,
    run_p0_plus_mapping,
    run_p0_plus_mapping_plus_stg,
    run_p0_plus_mapping_plus_stg_plus_quality,
    run_p0_plus_mapping_plus_stg_plus_quality_with_review,
    run_p0_plus_mapping_plus_stg_with_review,
    run_quality_only_from_stg,
    run_quality_only_from_stg_with_review,
    run_stg_only_from_mapping,
)
from app.api.routes_jobs_control_plane import (
    get_config_asset_route,
    list_config_assets_route,
    publish_config_asset_route,
    router as control_plane_router,
    save_config_asset_route,
    validate_config_asset_route,
)
from app.api.routes_jobs_delivery import (
    assess_governance_readiness_route,
    batch_snapshots_route,
    build_governance_delivery_package_route,
    build_governance_work_package_route,
    compare_governance_snapshots_route,
    export_confirmation_workbooks_route,
    governance_delivery_manifest_route,
    governance_readiness_summary_route,
    import_confirmation_and_rerun_route,
    import_confirmation_workbook_route,
    roundtrip_changed_objects_summary_route,
    router as delivery_router,
    run_batch_governance_route,
    run_incremental_rerun_route,
    validate_confirmation_workbook_route,
)
from app.api.routes_jobs_quality import (
    build_execution_ready_package_route,
    execution_package_summary_route,
    export_confirmed_quality_rules_route,
    export_execution_ready_package_route,
    list_review_summary,
    quality_rule_review_summary_route,
    review_quality_rules_route,
    router as quality_router,
    save_mapping_review,
    save_stg_review,
)
from app.api.routes_jobs_intake import (
    diagnose_confirmation_template,
    diagnose_metadata_intake_template,
    get_domain_governance_packs,
    get_project_templates,
    import_confirmation_template_and_rerun,
    import_confirmation_with_template,
    match_domain_governance_pack,
    normalize_metadata_input,
    run_governance_with_intake_profile,
    run_project_template,
    router as intake_router,
)
from app.api.routes_jobs_tools import (
    agent_shell_plan,
    agent_shell_resolve_context,
    agent_shell_run,
    agent_shell_session,
    capability_manifest_route,
    call_tool_route,
    get_trace_route,
    invoke_native_tool_route,
    invoke_openai_tool_route,
    list_recent_traces_route,
    list_tools_route,
    mcp_tool_manifest_route,
    native_tool_schemas_route,
    openai_tool_schemas_route,
    router as tools_router,
)

router = APIRouter(prefix="/jobs", tags=["jobs"])
router.include_router(intake_router)
router.include_router(core_router)
router.include_router(tools_router)
router.include_router(control_plane_router)
router.include_router(quality_router)
router.include_router(delivery_router)
router.include_router(backlog_router)

__all__ = [
    "AgentShellPlanRequest",
    "AgentShellRunRequest",
    "BatchGovernanceRequest",
    "BatchSnapshotCompareRequest",
    "ConfigAssetSaveRequest",
    "ConfirmationTemplateRequest",
    "ConfirmationWorkbookImportRequest",
    "ConfirmedQualityRuleExportRequest",
    "DomainPackMatchRequest",
    "ExecutionPackageBuildRequest",
    "ExecutionPackageExportRequest",
    "FileRunRequest",
    "GovernanceBacklogBuildRequest",
    "GovernanceBacklogStatusUpdateRequest",
    "GovernanceDeliveryPackageRequest",
    "GovernancePortfolioAssessmentRequest",
    "GovernanceReadinessAssessmentRequest",
    "GovernanceWorkPackageBuildRequest",
    "IntentTextRequest",
    "MappingReviewSaveRequest",
    "MetadataIntakeRequest",
    "NativeToolInvokeRequest",
    "OpenAIToolInvokeRequest",
    "ProgressSnapshotRequest",
    "ProjectTemplateRunRequest",
    "QualityRuleReviewRequest",
    "StgReviewSaveRequest",
    "agent_shell_plan",
    "agent_shell_resolve_context",
    "agent_shell_run",
    "agent_shell_session",
    "assess_governance_portfolio_route",
    "assess_governance_readiness_route",
    "batch_snapshots_route",
    "build_execution_ready_package_route",
    "build_governance_backlog_route",
    "build_governance_delivery_package_route",
    "build_governance_work_package_route",
    "call_tool_route",
    "capability_manifest_route",
    "compare_governance_snapshots_route",
    "diagnose_confirmation_template",
    "diagnose_metadata_intake_template",
    "execution_package_summary_route",
    "export_confirmation_workbooks_route",
    "export_confirmed_quality_rules_route",
    "export_execution_ready_package_route",
    "generate_progress_snapshot_route",
    "get_config_asset_route",
    "get_domain_governance_packs",
    "get_project_templates",
    "get_trace_route",
    "governance_backlog_route",
    "governance_backlog_summary_route",
    "governance_delivery_manifest_route",
    "governance_portfolio_summary_route",
    "governance_progress_snapshots_route",
    "governance_readiness_summary_route",
    "import_confirmation_and_rerun_route",
    "import_confirmation_template_and_rerun",
    "import_confirmation_with_template",
    "import_confirmation_workbook_route",
    "interpret_governance_task",
    "invoke_native_tool_route",
    "invoke_openai_tool_route",
    "list_config_assets_route",
    "list_jobs",
    "list_recent_traces_route",
    "list_review_summary",
    "list_tools_route",
    "list_workflow_profiles",
    "match_domain_governance_pack",
    "mcp_tool_manifest_route",
    "native_tool_schemas_route",
    "normalize_metadata_input",
    "openai_tool_schemas_route",
    "publish_config_asset_route",
    "quality_rule_review_summary_route",
    "review_quality_rules_route",
    "roundtrip_changed_objects_summary_route",
    "router",
    "run_batch_governance_route",
    "run_governance_task_route",
    "run_governance_with_intake_profile",
    "run_incremental_rerun_route",
    "run_interpreted_governance_task",
    "run_mapping_only",
    "run_p0_demo",
    "run_p0_from_file",
    "run_p0_plus_mapping",
    "run_p0_plus_mapping_plus_stg",
    "run_p0_plus_mapping_plus_stg_plus_quality",
    "run_p0_plus_mapping_plus_stg_plus_quality_with_review",
    "run_p0_plus_mapping_plus_stg_with_review",
    "run_project_template",
    "run_quality_only_from_stg",
    "run_quality_only_from_stg_with_review",
    "run_stg_only_from_mapping",
    "save_config_asset_route",
    "save_mapping_review",
    "save_stg_review",
    "update_governance_backlog_status_route",
    "validate_config_asset_route",
    "validate_confirmation_workbook_route",
]
